GET https://dailyexcuses.azurewebsites.net/list



// OPTIONS https://localhost:5001

//GET https://localhost:5001/randomExcuse

//POST https://dailyexcuses.azurewebsites.net/New
#POST https://localhost:5001/New
//POST https://dailyexcuses.azurewebsites.net/New
//Content-Type: application/json

//"Para a semana vejo-te isso!"
